#!/usr/bin/env ruby -w

require 'lib/arguments_parser'
require 'lib/directory_watcher'
require 'lib/fsnooper'

if __FILE__ != nil
	
	trap('INT') do
		puts '\nQuitting...'
		exit
	end

	@fsnooper = FSnooper.new ARGV

	loop do
		@fsnooper.run
		sleep 3
	end

end
